// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aulglvwwjseidaxdxxqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1bGdsdnd3anNlaWRheGR4eHF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxOTczNjcsImV4cCI6MjA3Mjc3MzM2N30.EGB7Y9esju0hpA7fKrEIp9pJG8C2fpn8hEbHFcXHBXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});